### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by SFoster84** [mtourne/mecha#1]
Hi, thanks for providing your files, could you provide a license file for what license they are offered under?

**Comment by mtourne** [comment]
haven't touched any of this in a while

assume it's basically a BSD license! what do ppl use for open source 3d parts ? CC ? lmk ill add it

**Comment by SFoster84** [comment]
Yeah, I think CC is good, thanks!

**Comment by mtourne** [comment]
I ended up picking CC by-sa 

lmk if this is permissive enough for what you intend.

**Comment by SFoster84** [comment]
perfect!
